#Image of the openjdk
FROM openjdk:17-jdk-alpine
#Build context into the root folder of our container with the name app.jar.
COPY discovery_server/out/artifacts/discovery_server_jar/discovery_server.jar app.jar
#Start to run the app
ENTRYPOINT ["java","-jar","/app.jar"]