version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'iStudent'
      MYSQL_ROOT_PASSWORD: '12345' #Password for root access
    ports:
      - '3333:3306'
    expose: # Opens port 3306 on the container
      - '3333'
    volumes: # Where our data will be persisted
      - istudent:/var/lib/mysql

volumes:
  istudent:
    driver: local