# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/api_gateway/target/*.jar

COPY $JAR_FILE /app/api_gateway.jar
# Expose the port the app runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/api_gateway.jar"]