# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/club_service/target/*.jar

COPY $JAR_FILE /app/club_service.jar
# Expose the port the app runs on
EXPOSE 8081

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/club_service.jar"]