# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/town_service/target/*.jar

COPY $JAR_FILE /app/town_service.jar
# Expose the port the app runs on
EXPOSE 8081

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/town_service.jar"]