# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/parents_service/target/*.jar

COPY $JAR_FILE /app/parents_service.jar
# Expose the port the app runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/parents_service.jar"]