# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/saga_orchestrator/target/*.jar

COPY $JAR_FILE /app/saga_orchestrator.jar
# Expose the port the app runs on
EXPOSE 8080

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/saga_orchestrator.jar"]