# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/discovery_server/target/*.jar

COPY $JAR_FILE /app/discovery_server.jar
# Expose the port the app runs on
EXPOSE 8761

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/discovery_server.jar"]