#
# Build stage
#
FROM eclipse-temurin:17-jdk-jammy AS build

ENV HOME=/usr/app
RUN mkdir -p $HOME
WORKDIR $HOME
ADD ./club_service $HOME
RUN --mount=type=cache,target=/root/.m2 ./mvnw -f $HOME/pom.xml clean package

# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/usr/app/target/*.jar

COPY --from=build $JAR_FILE /app/club_service.jar
# Expose the port the app runs on
EXPOSE 8081

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/club_service.jar"]