# Works on jdk 17
FROM openjdk:17
ARG JAR_FILE=/students_service/target/*.jar

COPY $JAR_FILE /app/students_service.jar
# Expose the port the app runs on
EXPOSE 8082

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/students_service.jar"]